services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
  db:
    image: postgres:14.11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password